### ISSUE TITLE
Validation bug: Uploading an excel sheet causes error

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-parse-cloud#88]
On epilab-dev:

Uploading an excel sheet causes the following error:

error: Unable to create a submission {"code":141,"stack":"Error\n    at new BaseError (.../mibi-parse-cloud/lib/src/modules/shared/core/base-error.js:14:22)\n    at new UseCaseError (.../mibi-parse-cloud/lib/src/modules/shared/useCases/use-case.error.js:5:1)\n    at new SubmissionCreationFailedError (.../mibi-parse-cloud/lib/src/modules/orders/useCases/parse-sample-data/parse-sample-data.error.js:5:1)\n    at parseSampleDataController (.../mibi-parse-cloud/lib/src/modules/orders/useCases/parse-sample-data/parse-sample-data.controller.js:32:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
info DefaultSamplesController.putSamples has thrown an error. AxiosError: Request failed with status code 400
::ffff:127.0.0.1 - - [08/Oct/2024:15:33:30 +0000] "PUT /v2/samples HTTP/1.1" 500 47 "http://localhost:4200/samples/upload" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by dptolle** [comment]
This bug was caused by the Ansprechpartner entry in the Einsendebogen holding an email address instead of a name.  The field should now accept either

**Comment by afalenski** [comment]
- Uploading an Einsendebogen with a name in C20 and an email address in C22 worked.
- Uploading an Einsendebogen with an email address in C20 and a name in C22 did not work. No data was uploaded. Error toaster message: "Es gab einen Fehler beim Importieren der Datei."
- Uploading an Einsendebogen with empty C20 and C22 did not work. No data was uploaded. Error toaster message: "Es gab einen Fehler beim Importieren der Datei."
- Uploading an Einsendebogen without any text in the yellow cells in the first 32 rows did not work. No data was uploaded. Error toaster message: "Es gab einen Fehler beim Importieren der Datei."
All Einsendebögen were accepted by the productive portal.
Please fix.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
Einsendebogen-v17_NRL-AR_TEST.xlsx
mpcl88_Einsendebogen-v17_NRL-AR_AnsprechpartnerEmail.xlsx
mpcl88_Einsendebogen-v17_NRL-AR_KeinAnsprechpartnerEmail.xlsx
mpcl88_Einsendebogen-v17_NRL-AR_FormularLeer.xlsx

Browsers:
- Firefox 128.5.2esr (64-Bit)

**Comment by afalenski** [comment]
- Uploading an Einsendebogen without any metadata except for the email address works.
- Uploading an Einsendebogen with an email address in both fields "Ansprechpartner" and "Email-Adresse" works.
An appropriate warning for a missing email adress will be implemented via another ticket.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
Einsendebogen-v17_NRL-AR_TEST.xlsx
mpcl88_Einsendebogen-v17_NRL-AR_FormularLeerAußerEmail.xlsx
mpcl88_Einsendebogen-v17_NRL-AR_FormularLeerAußerEmail_inC20u22.xlsx

Browsers:
- Firefox 128.5.2esr (64-Bit)
